### ISSUE TITLE
Add a tab manually to group

### ISSUE THREAD

**Issue by akshgpt7** [osdc/TabuRei#27]
Add a `+` button at the end of tab list to add a tab manually to the group.

**Comment by PrimalPimmy** [comment]
But how will you make this work? Like what'll open after you click the `+` button? A drop down box showing all current open tabs and choose from there? or something else?

**Comment by akshgpt7** [comment]
I started working on this a while back, will continue soon. The `+` button will open up a text input field where you can enter a URL manually, and that will be added to the tab group.
