### ISSUE TITLE
Use a div as tab list container instead of ul

### ISSUE THREAD

**Issue by daemon1024** [osdc/TabuRei#35]
We used list for the tab list earlier but now we have wrapped each element inside a particular div. So the `ul` tag is redundant now cause we are not using html list for tab list ( pretty ironic xD ). We need to update the `ul` container to a `div` with suitable class name and properties.

**Comment by akshgpt7** [comment]
Go ahead @aadishjain08! Let us know if you have any questions.

**Comment by daemon1024** [comment]
Hey @aadishjain08, Just to provide some context
https://github.com/osdc/TabuRei/blob/e7e0c6f04f6935fd9a6ab471dcf4951847e330fd/js/tab-manager.js#L182
Here you can see the `ul` tag, but the followup child elements are all div
https://github.com/osdc/TabuRei/blob/e7e0c6f04f6935fd9a6ab471dcf4951847e330fd/js/tab-manager.js#L188

So the `ul` is the part that needs to be handled. Feel free to reach out to us in this thread or on our [discord channel](https://discord.gg/asdUYZmmZj) if you have any more queries :)
Thanks a lot for picking this up 🚀

**Comment by aadishjain08** [comment]
Hey @daemon1024, I have raised a pull request to resolve this issue. Please have a look and let me know if there are any changes required.
https://github.com/osdc/TabuRei/pull/74
Thanks!
