### ISSUE TITLE
Fix responsive behavior under 648 length

### ISSUE THREAD

**Issue by akshgpt7** [osdc/TabuRei#36]
The responsiveness is dicey under the length of 648.

**Comment by vmk8826** [comment]
can you please elaborate what needs to be done?

**Comment by daemon1024** [comment]
Hey @vmk8826, Thanks for your interest in this. 
![unknown](https://user-images.githubusercontent.com/47106543/110233598-f171b300-7f4a-11eb-84b4-bd90f7f7c10f.png)

When we see the manager page in smaller width windows < 648px long it seems to behave wierdly i.e. not responsive. So we want to make this page responsive :)

More about responsive design here https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design

Lmk if you want to work on this, will assign it to you :D

**Comment by vmk8826** [comment]
okay I want to work on this

**Comment by sarthakpant772** [comment]
hey i am interested in this i might have fixed this issue too i guess. I have come up with this or do u want it be on same line as of .title
![image](https://user-images.githubusercontent.com/67951999/129599696-d0cf39d4-23b3-4547-8931-e5abde13fdc6.png)

**Comment by daemon1024** [comment]
@sarthakpant772 Thank You, LGTM. Please make a PR so we can review and continue further discussion there.
