### ISSUE TITLE
Add an option to restore all tabs in a new browser window.

### ISSUE THREAD

**Issue by PrimalPimmy** [osdc/TabuRei#44]
More stuff to improve workflow, if I'm currently working on my current window and don't want other tabs brought here, I wish to be able to restore tabs if I need in a new window.

**Comment by akshgpt7** [comment]
Makes sense, sounds like a nice feature. The only thing I'm thinking is that adding a separate button of "Restore all in new window" might be a little clutter. What do you think?

**Comment by PrimalPimmy** [comment]
Yeah, I was think if there was a drop down menu as we click on the restore button to restore in current window or in a new window, although that'd also be two clicks to restore instead of direct restore... Oh what if we added a keyboard shortcut, like for example press Ctrl + click on restore to restore tabs in a new window, and if nothing is pressed, just restore in current window.

**Comment by PrimalPimmy** [comment]
I'd like to work on this issue, thinking of implementing right-click to directly open all tabs in a new window.

**Comment by daemon1024** [comment]
Middle click maybe?
