### ISSUE TITLE
Add "copy text" button for the Export field

### ISSUE THREAD

**Issue by akshgpt7** [osdc/TabuRei#60]
It's kinda tedious to select the entire list manually and copy it (on the Export page). Having a "copy text" button on the top of the field that copies the text to clipboard will be great.

**Comment by dkoode** [comment]
Hey there, i've created the button you ask for. I hope you guys are open to outsşde contributions. It looks like this;
![Ekran Resmi 2021-08-09 20 16 32](https://user-images.githubusercontent.com/81515348/128747992-f6312d2c-882c-47ca-bd3d-e6b6d5cf0720.png)

**Comment by daemon1024** [comment]
We are definitely open and welcome any kind of contribution :D Thanks a lot @dkoode for the the pull request, I have left some comments on the PR :D
