### ISSUE TITLE
Have something on the screen when there are no tab groups

### ISSUE THREAD

**Issue by akshgpt7** [osdc/TabuRei#66]
Initially, when there are no tab groups, the screen only has the buttons, which look pretty odd:

![image](https://user-images.githubusercontent.com/20405311/131049104-a27faafa-e327-40da-81c2-7472158cf64a.png)

Having some kind of an empty box (like a tab group) with text like "Save some tabs already!" or anything cool will be nice.

**Comment by bhandarii7** [comment]
can I work on this issue.

**Comment by daemon1024** [comment]
Resolved via #69
